# Change these first
owner: aptive-env # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Aptive Corporate
    url: https://www.goaptive.com
  - name: Branch Manager
    url: https://bmapi.aptive.guru/users/getQuotes
  - name: Field Service
    url: https://api.field-services.prd.goaptive.com
  - name: Guru
    url: https://apistats.aptive.guru
  - name: Onboarding
    url: https://api.onboarding.prd.goaptive.com
  - name: Notifications
    url: https://api.notifications.prd.goaptive.com
  - name: Payment Service API
    url: https://api.payment-service.prd.goaptive.com
  - name: Sales API
    url: https://api.sales-app.prd.goaptive.com/health-check
  - name: Sales Planning Tool
    url: https://spt-api.rep-services.prd.goaptive.com/api/documentation
  - name: Streetsmarts
    url: https://api.street-smarts.prd.goaptive.com/health-check
  - name: Customer Portal
    url: https://api.customer-portal.prd.goaptive.com
  - name: Plan Builder
    url: https://api.plan-builder.prd.goaptive.com/health-check
  - name: Product Manager
    url: https://api.product-manager.prd.goaptive.com/health-check
  - name: Self Service
    url: https://api.self-service.prd.goaptive.com/healthcheck

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.aptivetech.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/aptive-env/status/master/assets/logo.svg
  # themeUrl: https://raw.githubusercontent.com/aptive-env/status/master/assets/aptive.css
  theme: dark
  name: Aptive Technology Status
  introTitle: ""
  introMessage: This is the status of services maintained by Aptive Environmental.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: DataDog
      href: https://us5.datadoghq.com/dashboard/r8q-n2s-9jf/service-health-all-services?refresh_mode=sliding&view=spans&from_ts=1704323353148&to_ts=1704324253148&live=true

i18n:
  footer: Aptive Environmental, LLC

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
